const subjects = [
    "You",
    "Your dreams",
    "The future",
    "Life",
    "Success",
    "Happiness",
    "Courage",
    "Positivity",
    "Strength",
    "Hope",
    "Love",
    "Belief",
    "Change",
    "Challenges",
    "Opportunities",
    "Persistence",
    "Faith",
    "Gratitude",
    "Kindness",
    "Wisdom",
    "Passion",
    "Creativity",
    "Imagination",
    "Growth",
    "Potential",
    "Purpose",
    "Mindset",
    "Determination",
    "Resilience",
    "Confidence",
    "Joy",
    "Focus",
    "Optimism",
    "Inspiration",
    "Aspirations",
    "Ambitions",
    "Dreams",
    "Goals",
    "Motivation",
    "Self-worth",
    "Positivity",
    "Inner peace",
    "Harmony",
    "Balance",
    "Discovery",
    "Innovation",
    "Adventure",
    "Triumph",
    "Perseverance",
    "Discovery",
    "Intuition",
    "Transformation",
    "Empowerment",
    "Reflection",
    "Purpose",
    "Adventure",
    "Connection",
    "Simplicity",
    "Mindfulness",
    "Serenity",
    "Wholeness",
    "Well-being",
    "Grace",
    "Courage",
    "Potential",
    "Vision",
    "Integrity",
    "Diversity",
    "Imagination",
    "Optimism",
    "Creativity",
    "Innovation",
    "Kindness",
    "Empathy",
    "Authenticity",
    "Progress",
    "Balance",
    "Joy",
    "Love"
  ];
  
  const verbs = [
    "empowers",
    "inspires",
    "transforms",
    "nurtures",
    "fuels",
    "encourages",
    "drives",
    "challenges",
    "motivates",
    "strengthens",
    "uplifts",
    "elevates",
    "guides",
    "forges",
    "ignites",
    "cultivates",
    "fosters",
    "awakens",
    "propels",
    "enriches",
    "invigorates",
    "impels",
    "catapults",
    "sparks",
    "spurs",
    "stirs",
    "awakens",
    "propels",
    "enriches",
    "invigorates",
    "impels",
    "catapults",
    "sparks",
    "spurs",
    "stirs"
  ];
  
  const objects = [
    "growth",
    "greatness",
    "success",
    "happiness",
    "fulfillment",
    "wisdom",
    "creativity",
    "imagination",
    "potential",
    "dreams",
    "goals",
    "aspirations",
    "opportunities",
    "possibilities",
    "change",
    "joy",
    "love",
    "peace",
    "harmony",
    "courage",
    "kindness",
    "gratitude",
    "resilience",
    "positivity",
    "purpose",
    "connection",
    "innovation",
    "empowerment",
    "inspiration",
    "transformation",
    "integrity",
    "progress",
    "vision",
    "authenticity",
    "kindness",
    "compassion",
    "positivity",
    "belief",
    "optimism",
    "mindfulness",
    "balance",
    "serenity",
    "wholeness",
    "well-being"
  ];
  
  function getRandomIndex(arr) {
    return Math.floor(Math.random() * arr.length);
  }
  
  function generateInspirationalQuote() {
    const subject = subjects[getRandomIndex(subjects)];
    const verb = verbs[getRandomIndex(verbs)];
    const object = objects[getRandomIndex(objects)];
  
    return `${subject} ${verb} ${object}.`;
  }
  
  // Example usage
  const randomQuote = generateInspirationalQuote();
  console.log(randomQuote);

  